"""add_sku_disabled

Revision ID: 250254b16e2b
Revises: 78eaf291de9e
Create Date: 2022-06-11 15:29:15.662693

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "250254b16e2b"
down_revision = "78eaf291de9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sku", sa.Column("disabled", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_sku_disabled"), "sku", ["disabled"], unique=False)
    op.alter_column(
        "warehouse_invoice", "status", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "warehouse_invoice", "status", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_index(op.f("ix_sku_disabled"), table_name="sku")
    op.drop_column("sku", "disabled")
    # ### end Alembic commands ###
