"""add created date and index on invoice

Revision ID: a995597d45af
Revises: 82714127ef1d
Create Date: 2022-05-23 17:08:20.594666

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a995597d45af"
down_revision = "82714127ef1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("created_date", sa.DateTime(), nullable=True))
    op.create_index(
        "idx_orderedby_created_date",
        "invoice",
        ["created_date"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_orderedby_created_date", table_name="invoice", postgresql_using="btree"
    )
    op.drop_column("invoice", "created_date")
    # ### end Alembic commands ###
