"""update invoice table

Revision ID: 038b1bf8edc7
Revises: a995597d45af
Create Date: 2022-05-23 17:39:23.689201

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "038b1bf8edc7"
down_revision = "a995597d45af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice", sa.Column("quantities", sa.ARRAY(sa.Integer()), nullable=False)
    )
    op.alter_column("invoice", "invoice_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "invoice",
        "items",
        existing_type=postgresql.ARRAY(postgresql.UUID()),
        nullable=False,
    )
    op.alter_column("invoice", "company", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("invoice", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "invoice", "created_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(
        op.f("ix_invoice_invoice_id"), "invoice", ["invoice_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_invoice_id"), table_name="invoice")
    op.alter_column(
        "invoice", "created_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("invoice", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("invoice", "company", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "invoice",
        "items",
        existing_type=postgresql.ARRAY(postgresql.UUID()),
        nullable=True,
    )
    op.alter_column("invoice", "invoice_id", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("invoice", "quantities")
    # ### end Alembic commands ###
