"""add warehouse_invoice status

Revision ID: 78eaf291de9e
Revises: a718fc89dd64
Create Date: 2022-06-10 11:10:41.968927

"""
from typing import List

import sqlalchemy as sa
from sqlalchemy.orm import load_only
from sqlalchemy.orm.session import Session

from alembic import op
from app.models import WarehouseInvoice
from app.schemas.invoice import Status

# revision identifiers, used by Alembic.
revision = '78eaf291de9e'
down_revision = 'a718fc89dd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_invoice', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###
    
    session = Session(bind=op.get_bind())

    query = sa.select(WarehouseInvoice).options(load_only("id", "status"))
    warehouse_invoices: List[WarehouseInvoice] = session.execute(query).scalars().all()
    
    for warehouse_invoice in warehouse_invoices:
        warehouse_invoice.status = Status.DELIVERED

    session.commit()

    op.alter_column('invoice', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False
            )

    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_invoice', 'status')
    # ### end Alembic commands ###
