"""add warehouse_invoice_details table

Revision ID: ef5fe29e6871
Revises: 250254b16e2b
Create Date: 2022-06-11 16:17:16.730650

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ef5fe29e6871'
down_revision = '250254b16e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_invoice_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('warehouse_invoice_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_per_item', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('sku_variants', postgresql.ARRAY(postgresql.UUID()), nullable=True),
    sa.Column('rows', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('columns', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('quantities', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_invoice_id'], ['warehouse_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_invoice_details_id'), 'warehouse_invoice_details', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_invoice_details_warehouse_invoice_id'), 'warehouse_invoice_details', ['warehouse_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_invoice_details_warehouse_invoice_id'), table_name='warehouse_invoice_details')
    op.drop_index(op.f('ix_warehouse_invoice_details_id'), table_name='warehouse_invoice_details')
    op.drop_table('warehouse_invoice_details')
    # ### end Alembic commands ###
