"""reinsert table image

Revision ID: 6f0943512589
Revises: 506f308229b7
Create Date: 2022-06-02 13:43:17.334756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from fastapi_users_db_sqlalchemy import guid
# revision identifiers, used by Alembic.
revision = '6f0943512589'
down_revision = '506f308229b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('base64', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', guid.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.add_column('sku', sa.Column('image_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'sku', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sku', type_='foreignkey')
    op.drop_column('sku', 'image_id')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
