"""add reference to active_parent sku

Revision ID: 3d268c7b9abc
Revises: ef5fe29e6871
Create Date: 2022-07-01 17:55:50.751511

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d268c7b9abc"
down_revision = "ef5fe29e6871"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sku",
        sa.Column("active_parent_sku_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, "sku", "sku", ["active_parent_sku_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sku", type_="foreignkey")
    op.drop_column("sku", "active_parent_sku_id")
    # ### end Alembic commands ###
